[project]
name = "data-script-template"
version = "0.1.0"
description = "Template para scripts Python focados em ETL leve e reutilizável."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "gabrielhmango", email = "gabrielhmango@gmail.com" }
]
dependencies = [
    "click==8.3.2",
    "colorama==0.4.6",
    "python-dotenv==1.2.2",
    "SQLAlchemy==2.0.49",
    "pymongo==4.16.0"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.taskipy.tasks]
hello = "echo 'Woring...'"
config_git_user = 'git config --global user.name "gabrielhmango"'
config_git_email = 'git config --global user.email "gabrielhmango@gmail.com"'
config_git_list = "git config --global --list"
config_git = "task config_git_user && task config_git_email && task config_git_list"
requirements = "pip freeze > requirements.txt"
format = "blue . && isort ."
pre_commit = 'task format && task requirements && task config_git && git status && git add . && git status'
commit = "git commit -m"
post_commit = "git push"
run = "python main.py"

[tool.blue]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
